### ISSUE TITLE
ROUND | Controller Settings Has Incorrect Outlines

### ISSUE THREAD

**Issue by Ian-Boraks** [EMERALD0874/Steam-Deck-Themes#14]
Controller Settings Has Incorrect Outlines

![Full Screen](https://user-images.githubusercontent.com/31255827/182192415-9170b0e9-8546-4073-8cae-4bfd4c7c21b9.png)

![Zoomed In](https://user-images.githubusercontent.com/31255827/182192392-e26c147d-ed14-4152-80c8-32377c7a5084.png)

![Full Screen](https://user-images.githubusercontent.com/31255827/182192985-0d34332a-fba6-40d9-b2f5-9994843501af.png)

![Zoomed In](https://user-images.githubusercontent.com/31255827/182193054-888f0f97-2d35-45ce-857f-8cef2c2bee51.png)

**Comment by EMERALD0874** [comment]
Closed by #24
