### ISSUE TITLE
Centered Home - Breaks at different resolutions

### ISSUE THREAD

**Issue by EMERALD0874** [EMERALD0874/Steam-Deck-Themes#23]
I can probably add support for all resolutions but forgot to originally. Expect this in the near future.

**Comment by EMERALD0874** [comment]
Tried working on this, but the math is proving more difficult than I thought because of how the UI scales. This may take a while.

**Comment by cKSilent** [comment]
I am not sure if this is related to scaling or CSS but centered home does not appear to be working on the CSS loader for Windows. I am on the ROG Ally and would love for this theme to work in big picture mode. Right now it still keeps the what’s new / friends / recommend without pushing it down out of the way. For what it’s worth, I have seen some other themes scale appropriately for big picture mode on this Ally display. Thoughts?

**Comment by EMERALD0874** [comment]
Decky Loader is only officially supported on Steam Deck so the theme is centered around that given I haven't found a good CSS solution for all resolutions. You're welcome to work on a fix if you'd like, this isn't a high-priority item for me
