### ISSUE TITLE
ROUND | Switch Like Home bug

### ISSUE THREAD

**Issue by OuterWinnie** [EMERALD0874/Steam-Deck-Themes#25]
While using the Round theme along with  Switch Like Home, it seems to displace and not fit correctly after entering in a game library page and coming back to home:
https://streamable.com/hk2che

**Comment by EMERALD0874** [comment]
Will be treated as a bug to attempt better compatibility with other themes. Will be fixed and (hopefully) updated in the theme database by the end of the day.

**Comment by EMERALD0874** [comment]
Never mind, my fix doesn't appear to be working. Going to keep investigating.
