### ISSUE TITLE
Request: Add "Josefin Sans" to Fonts

### ISSUE THREAD

**Issue by aroonk** [EMERALD0874/Steam-Deck-Themes#31]
I believe you've encouraged users to request fonts via an issue on the GitHub repository, so I'm requesting addition of the "Josefin Sans" font:
https://fonts.google.com/specimen/Josefin+Sans

The font family is licensed under the Open Font License (OFL), so "You can use them in your products & projects – print or digital, commercial or otherwise."

I'm currently using this font throughout my phone's UI (via Niagara Launcher) and I think it's readable and lovely. Cheers!

**Comment by EMERALD0874** [comment]
I've been pretty busy recently, but I'll do my best to get to this when possible.

**Comment by EMERALD0874** [comment]
I know I'm late as hell, but I should be able to do this sometime soon. Expect a release this week.

**Comment by aroonk** [comment]
Thanks, using it now!!
