### ISSUE TITLE
New update stable 3.3.2 breaks color Obsidian theme

### ISSUE THREAD

**Issue by TheKerevas** [EMERALD0874/Steam-Deck-Themes#32]
The latest SteamOS update made the SteamOS home two-colored and no longer all black

![IMG_20221006_143746](https://user-images.githubusercontent.com/101466273/194314383-55a9b19d-3a21-48fd-bc4a-0efb0c3a75ae.jpg)

**Comment by EMERALD0874** [comment]
Resolved on the store in https://github.com/suchmememanyskill/CssLoader-ThemeDb/pull/102
