### ISSUE TITLE
Request: Add the “Torus Pro” to Fonts.

### ISSUE THREAD

**Issue by Sonic0009** [EMERALD0874/Steam-Deck-Themes#34]
I saw that you can request fonts here, so I would like to request the font “Torus Pro” to be added: https://befonts.com/torus-pro-font.html

**Comment by EMERALD0874** [comment]
Will do this when I have the time.

**Comment by EMERALD0874** [comment]
The download provided appears to be a demo version with multiple characters (4, |, #) replaced with a demo character. Could you find another download that contains all characters and is licensed for personal use?

**Comment by Sonic0009** [comment]
I found another link that could be it but I’m not sure myself as it appears to be a “premium” version of it, if the only way to get the whole thing is to buy it then I have no problem in helping out with that.

Links: 
https://ifonts.xyz/torus-pro-font.html

**Comment by EMERALD0874** [comment]
I have decided not to add this font since I have had trouble finding a free version. However, I have added the ability to add your own fonts easily locally through the latest patch. Hopefully this should suffice! :)
