### ISSUE TITLE
Adding Va-11 hall-a font. 

### ISSUE THREAD

**Issue by TheRealRws** [EMERALD0874/Steam-Deck-Themes#37]
Could you add this font?

https://fontstruct.com/fontstructions/show/1323621/va-11-hall-a-cyr-10px

**Comment by EMERALD0874** [comment]
Upon further investigation, it seems this is the font you were referencing. Is this correct? https://www.dafont.com/cyberpunkwaifus.font

**Comment by TheRealRws** [comment]
Yes! There are multiple vesions of the same font floating about. But it is the font I would love to be added.

**Comment by EMERALD0874** [comment]
I have decided not to add this font due to copyright concerns since it is exclusive to specific software. However, I have added the ability to add your own fonts easily locally through the latest patch. Hopefully this should suffice! :)
