### ISSUE TITLE
Adding the DS Pokémon game font request

### ISSUE THREAD

**Issue by CrimsonLacerations** [EMERALD0874/Steam-Deck-Themes#38]
Hello, I'm requesting that you add the font used in Pokémon Diamond/Pearl/Platinum versions. Thanks much in advance. 

https://fontstruct.com/fontstructions/show/404271/pok_mon_dp_pro

**Comment by EMERALD0874** [comment]
Sorry for the late response. I feel that fonts made for specific games border on copyright eligibility and would be better suited for other themes specific to those games anyways.
