### ISSUE TITLE
Obsidian theme doesnt blur background edges

### ISSUE THREAD

**Issue by 06kellyjac** [EMERALD0874/Steam-Deck-Themes#41]
Im using the obsidian theme which is really nice except it's quite jaring to see the sharp edges of the game backgrounds on the home screen when swapping between games.
This is quite clear both for normal home and when using centered home

Either adding the background blur back, or configuration options would be great

Thanks

---

Edit: in the cover image for the theme there is blur so maybe it's just broken. Ive tried turning off all other css to make sure nothing is conflicting but the issue remains

**Comment by EMERALD0874** [comment]
I'll take a look at that this weekend. Thanks for the report.

**Comment by EMERALD0874** [comment]
Fixed with the latest patch. It should be on the CSS Loader store shortly!

**Comment by 06kellyjac** [comment]
Thanks!
