### ISSUE TITLE
RPGMaker 2000 Font Pack Request

### ISSUE THREAD

**Issue by WMan22** [EMERALD0874/Steam-Deck-Themes#45]
You can find it here https://www.deviantart.com/tabmok99/art/RPG-Maker-2000-Font-Pack-900800437
Easy download link in case you don't have a Deviantart account: https://www.mediafire.com/file/cyhjemiqfm26nj9/rpg_maker_2000_font_pack_by_tabmok99_dewba2d.zip/file

**Comment by EMERALD0874** [comment]
I have decided not to add this font due to copyright concerns since it is exclusive to specific software and I just added another bitmap font. However, I have added the ability to add your own fonts easily locally through the latest patch. Hopefully, this should suffice! :)
