### ISSUE TITLE
Phantom - Add "zig-zag" toggle

### ISSUE THREAD

**Issue by Toletheus** [EMERALD0874/Steam-Deck-Themes#47]
Minor issue - when using Phantom in combination with the "Switch Like Home" add-on, the zig-zag behind the icons on the home screen doesn't center vertically under the icons the same way as normal.  Still looks fine, but I would request that a toggle be added to turn optionally off the zig-zag pattern for users who don't care for it.

[Image with Phantom + Centered Home](https://steamcommunity.com/sharedfiles/filedetails/?id=2918566389)
[Image with Phantom + Switch Like Home](https://steamcommunity.com/sharedfiles/filedetails/?id=2918566231)

Thanks for your support!

**Comment by EMERALD0874** [comment]
Done!

**Comment by Toletheus** [comment]
Thank you!
