### ISSUE TITLE
Add LibreFranklin to Font options

### ISSUE THREAD

**Issue by rareyman** [EMERALD0874/Steam-Deck-Themes#48]
Hey! I would like to see LibreFranklin added as a font choice. I know it is similar to the default Steam font, but I feel it has a slightly more classic, yet simple feel to it. (I’ve been using it for my UI designs for a while and have gotten great results.) Check Pull Requests, as I have already implemented it on my own, but let me know if I missed anything.

Thanks!

**Comment by EMERALD0874** [comment]
Fonts is no longer accepting new fonts due to file size concerns. Please download the latest patch for an easy way to add a custom font.
