### ISSUE TITLE
Obsidian theme breaks lockscreen images from Minimal Lock Screen

### ISSUE THREAD

**Issue by NiceManiac** [EMERALD0874/Steam-Deck-Themes#52]
The obsidian theme makes the background on the plugin "Minimal Lock Screen" only a single color, even when using a picture. Disabling obsidian fixes the issue so this has to be obsidian doing some skinning that overwrites what minimal lock screen does. An option to disable skinning on the lock screen would be very appreciated

**Comment by NiceManiac** [comment]
I managed to fix this issue by removing the !important tag on the lockscreen segment in shared.css might want to add a toggle to turn that on or off for other people using the minimal lock screen plugin.

**Comment by Kazlehoff** [comment]
Obsidian is up to Ver 3.0 and this is still an issue... and theres a listed fix right here.

**Comment by NiceManiac** [comment]
> Obsidian is up to Ver 3.0 and this is still an issue... and theres a listed fix right here.

i did make a fork with an easy workaround but emerald does not seem to want to use that fix even though it is pretty minimal and fixes this issue. i am currently only using my fork on my steam deck to get around this problem. see #53

**Comment by Kazlehoff** [comment]
Appreciate the update, Emerald :) Hope the exams go/went well.

**Comment by EMERALD0874** [comment]
This is fixed by https://github.com/EMERALD0874/Steam-Deck-Themes/commit/4f9d5060e0707f2a26f6537552ddaabf55cba8cf. If you continue to have issues, make sure the Minimal Lock Screen theme is enabled after Obsidian. If you are still having issues, please reach out to their developers and ask them to add an `!important` flag to the background so it overrides Obsidian.

**Comment by Kazlehoff** [comment]
issue persists in most recent version

**Comment by EMERALD0874** [comment]
Disable both themes. Enable Obsidian first (lower precedence) then Minimal Lock Screen (higher precedence). If this doesn't fix your issue, please reach out to the developers of Minimal Lock Screen and ask them to consider adding `!important` given it only targets the lock screen and should override other more general themes.

I tested the above fix myself and it worked on my end.
