### ISSUE TITLE
Obsidian + custom loader

### ISSUE THREAD

**Issue by M2ljay** [EMERALD0874/Steam-Deck-Themes#57]
Obsidian no longer works with loading background on steamos beta/preview, on stable colors will be black, on beta/preview colors are default deck colors

**Comment by someone5678** [comment]
> Obsidian no longer works with loading background on steamos beta/preview, on stable colors will be black, on beta/preview colors are default deck colors

Should be addressed with https://github.com/EMERALD0874/Steam-Deck-Themes/pull/58 !
