### ISSUE TITLE
Obsidian - Incompatibility with Clean Gameview

### ISSUE THREAD

**Issue by yoyoys** [EMERALD0874/Steam-Deck-Themes#59]
only Clean Gameview plugin
![IMG_2411](https://github.com/EMERALD0874/Steam-Deck-Themes/assets/22124891/d2ffc442-9069-438a-b8a5-cffb218e5df4)

With obsidian
![IMG_2412](https://github.com/EMERALD0874/Steam-Deck-Themes/assets/22124891/cbeba2c6-d89a-4a82-856e-5aac1171260b)

So sad that I can’t see their boots.🥲
If there is a opacity option for gameview it will be great😆

**Comment by EMERALD0874** [comment]
I'll look into this but can't guarantee anything. Obsidian has a big issue with how often it uses `!important`, so I'm going to evaluate #28 first and see if I can at least make it so Clean Gameview can override Obsidian since it's a smaller theme.

**Comment by EMERALD0874** [comment]
After looking into this further, I think this is more of a Clean Gameview issue. If they're modifying the background of the play button area, it should be marked as `!important` if it's running into issues with Obsidian and other larger themes.
