### ISSUE TITLE
[Request] Playnite support

### ISSUE THREAD

**Issue by xoredg** [EMERALD0874/Steam-Deck-Themes#63]
Hello, might be a bit out of place but thought to ask regardless. I love these themes, specially Phantom. 
Is there any chance you could port them to Playnite so I can also use them (it?) in my desktop launcher / Windows handheld?

**Comment by suchmememanyskill** [comment]
Maybe slightly off-topic, but CSSLoader does have a windows release. So you can use it with big picture mode on windows.

**Comment by EMERALD0874** [comment]
CSS Loader doesn't support Playnite as far as I'm aware, so I have no plans to do this
