### ISSUE TITLE
Centered Home theme and 16th Nov. Steam update

### ISSUE THREAD

**Issue by MKReyesH** [EMERALD0874/Steam-Deck-Themes#66]
Hi! I just wanted to report that after the new Steam update the Centered Home theme does not hide the bottom tabs.

![20231116200353_1](https://github.com/EMERALD0874/Steam-Deck-Themes/assets/33583170/d7a38d75-8646-4edb-a0b9-7e7114346a3f)

Thank you very much for your work.

**Comment by EMERALD0874** [comment]
Will look at this sometime between now and next week. Thanks!

**Comment by EMERALD0874** [comment]
Resolved https://github.com/EMERALD0874/Steam-Deck-Themes/commit/d578a8d61616a86b8c97f9980c02e73f631f4eff
