### ISSUE TITLE
Remove blur on footer transparent now solid black

### ISSUE THREAD

**Issue by MoisteryMachine** [EMERALD0874/Steam-Deck-Themes#67]
The new update for Obsidian causes 'remove blur' on footer when transparent to be solid black, instead of actually transparent when its set to 0. This only happened in the newest update.

**Comment by EMERALD0874** [comment]
I believe you're describing intentional behavior. What "Remove Blur" is intended to do is replace the blur effects across the app with your chosen color, as making it transparent would make the text difficult to read.

If I'm mistaken, please describe this in more detail with screenshots.

**Comment by MoisteryMachine** [comment]
Before the last update, it wasnt cutting off the menu when used in combination with other CSS themes. Now it blacks out part of it:
![msg6091655988-787](https://github.com/EMERALD0874/Steam-Deck-Themes/assets/29517500/8440c50d-c590-469e-9958-ce6223fb79ce)

**Comment by EMERALD0874** [comment]
Could you give an example theme that conflicts and tell me what's blacked out? Still not sure I'm understanding but maybe this is a result of something Valve did with the new SteamOS update.
