### ISSUE TITLE
Obsidian - Recent Games custom color currently does nothing

### ISSUE THREAD

**Issue by ActuallyTheMoon** [EMERALD0874/Steam-Deck-Themes#68]
Choosing a custom color for recent game backgrounds doesn't do anything.

**Comment by ActuallyTheMoon** [comment]
Right now choosing a custom color for recent game backgrounds doesn't actually change the colour of the background (the pre set colours work fine)

**Comment by EMERALD0874** [comment]
Definitely didn't forget one line. Should be released in the next 24 hours. https://github.com/EMERALD0874/Steam-Deck-Themes/commit/8cd3e3c7de7d5d277d8dc9e20af026cf439b89fe
