### ISSUE TITLE
Obsidian doesn't apply theme to in game QAM header

### ISSUE THREAD

**Issue by rnikoopour** [EMERALD0874/Steam-Deck-Themes#73]
# Steps to Reproduce 
1. Open a game
2. Press the QAM button
3. View the header

I can't figure out how to take a screenshot of the QAM in game so I can't provide a screenshot.

**Comment by rnikoopour** [comment]
`.header_Header_1E_SL.header_InQuickAccess_2mRo5` is overwriting the background color

**Comment by EMERALD0874** [comment]
Solved by #74, please use keywords or link the issue to the PR in the future so your issues automatically close.
