### ISSUE TITLE
Round - Black borders in the download preview

### ISSUE THREAD

**Issue by pwnedCtrl** [EMERALD0874/Steam-Deck-Themes#80]
Since the latest Steam update the edges are no longer transparent, but have small black edges.
![download](https://github.com/EMERALD0874/Steam-Deck-Themes/assets/37429390/86f67016-4e04-48f5-8308-34b1367efcf6)

**Comment by EMERALD0874** [comment]
Fixed this and added rounding to the download bar! Will be released to DeckThemes soon.

![image](https://github.com/EMERALD0874/Steam-Deck-Themes/assets/11338953/43739a92-fc23-44a2-8f11-e0c314a336a3)
