### ISSUE TITLE
Round theme doesn't work for the menu items after SteamOS 3.6.8 Beta update

### ISSUE THREAD

**Issue by Sythog** [EMERALD0874/Steam-Deck-Themes#82]
Works fine for the game capsules and buttons. Doesn't work for QAM and Steam button menu items.

SteamOS 3.6.8 Beta
Decky 3.0.0-pre5

**Comment by EMERALD0874** [comment]
This may be related to CSS Loader being broken per the announcement in its Discord. If you're still having issues after an update, feel free to reach out again. https://discord.com/channels/1051660079033745478/1053060206298415114/1263588935708442734

**Comment by Sythog** [comment]
@EMERALD0874 I'm not sure I'm a member of that Discord server, hence can't see the announcement. Could you please share the server name?

**Comment by EMERALD0874** [comment]
https://discord.gg/HsU72Kfnpf
